name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile rename_pdf.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: rename-pdf-exe
        path: dist/rename_pdf.exe
